### ISSUE TITLE
dist, dist-prod files are not minified

### ISSUE THREAD

**Issue by dylanbussone** [vidstack/vidstack#654]
With v0.13.0+, the dist/* and dist-prod/* files stopped getting minified. It looks like it was something with the monorepo setup [commit](https://github.com/vidstack/vidstack/commit/d567312e8ccf21051ea218301d63d7afe5d5a3a8).

**Comment by mihar-22** [comment]
Hey @dylanbussone! Hope things are going well at Reddit. The minification was removed on purpose because it's an application-level concern. It should be minified by Rollup while bundling. You can take the minification further with the following config to mangle properties starting with `_`:

```js
// Assuming rollup terser plugin.
terser({
    mangle: {
      properties: {
        // avoid minifying double underscores __
        regex: /^_[a-z]/
      },
  },
});
```

**If logs are leaking again then this is a problem on our end.**

**Comment by mihar-22** [comment]
**If logs are leaking again then this is a problem on our end.**

**Comment by dylanbussone** [comment]
Hey, got it, just wanted to verify! Not seeing any log leak.
Things are going well, I just got us on vidstack 1.4.0 and things are looking great. The new custom loading strategy made our QoE timing determination a lot simpler. Hope all is well with you!
