### ISSUE TITLE
Loop attribute bug

### ISSUE THREAD

**Issue by zexingguo** [vidstack/vidstack#656]
The player won't loop play video correctly when the loop attribute is added. Here's a screen shot of the error in console.

<img width="798" alt="image" src="https://user-images.githubusercontent.com/11972292/164508638-94ef2607-918d-4302-845f-100e0cd16cdc.png">

Reproduce bug repo: https://github.com/zexingguo/vidstack-player-loop-bug

**Comment by mihar-22** [comment]
Thanks for the repro @zexingguo. This bug was in two parts, firstly property reflection would cause a client/server render mismatch so I removed them all for now, and secondly the loop prop was not taking effect because an event listener that handles it was not being attached.

I'll release shortly, thanks for your patience!
