### ISSUE TITLE
Updates to chapters.vtt do not show up on the player

### ISSUE THREAD

**Issue by connecteev** [vidstack/vidstack#910]
If I make any changes to my locally hosted chapters.vtt file, they don't get reflected in the player - even after clearing the browser cache and local storage. The player still displays the old chapters.

Note: here is my code...nothing special here, I am using the default HLS installation as mentioned on the [install](https://www.vidstack.io/docs/player/getting-started/installation/cdn/hls) page:

```
<!DOCTYPE html>
<html>
<head>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vidstack/styles/defaults.min.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vidstack/styles/community-skin/video.min.css" />
<script type="module" src="https://cdn.jsdelivr.net/npm/vidstack/dist/cdn/prod.js"></script>

</head>
<body>
    <media-player
        title="Name this video anything you want!"
        src="/456/original__video_file.m3u8"
        poster=""
        thumbnails="/456/thumbnails.vtt"
        aspect-ratio="16/9"
        crossorigin
    >
        <media-outlet>
            <media-poster
                alt="Girl walks into sprite gnomes around her friend on a campfire in danger!"
            ></media-poster>
            <track
                src="https://media-files.vidstack.io/sprite-fight/subs/english.vtt"
                label="English"
                srclang="en-US"
                kind="subtitles"
                default
            />
            <track
                src="/456/chapters.vtt"
                srclang="en-US"
                kind="chapters"
                default
            />
        </media-outlet>
        <media-community-skin></media-community-skin>
    </media-player>

</body>
</html>
```

**Comment by mihar-22** [comment]
This issue is outdated now and should be resolved since our new [`1.0@next` release](https://github.com/vidstack/vidstack/discussions/935). If the issue persits after upgrading, feel free to let me know here and we can reopen. If the issue has changed then please open a new one.

Do note, we don't perform any caching at the moment on any captions/chapters VTT files. There's no way for the player to remember the previous chapters. It must be some kind of caching happening at the browser or network level.
