### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'webkitSupportsPresentationMode')

### ISSUE THREAD

**Issue by reyamir** [vidstack/vidstack#947]
### Current Behavior:

vidstack with default layout get this error on console (chrome - windows 11)

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'webkitSupportsPresentationMode')
    at canUseVideoPresentation (vidstack-9bec6916.js:326:27)
    at new VideoProvider (vidstack-45b2f3a1.js:172:9)
    at VideoProviderLoader.load (vidstack-9bec6916.js:2237:12)
```

### Expected Behavior:

No error

**Comment by mihar-22** [comment]
Seems unusual because the video element is passed directly to the constructor of the `VideoProvider`. There's only one line where this code is called and it checks that for a missing element. I'm not on a Windows machine so I can't test this. I tested on Chrome/Mac with no problems.

Did you forget to include the `<MediaProvider>` component?
